<p><span style="color:#B22222"><strong>[Guide] Introduce Private Wiki</strong></span></p>

<p><strong>Requirements</strong></p>

<p>php 4.x or higher installed<br />
<span style="color:#800000"><strong>chmod -R 777 config<br />
chmod -R 777 tpl</strong></span></p>

<p>&nbsp;</p>

<p><strong>Described​</strong></p>

<p><span style="color:#800000"><strong>Wiki tpl file based storage without the need to separate DB</strong></span></p>

<p>Save wiki tpl is managed by config, tpl ID is generated by hash_key,<br />
corresponding to the key criteria config / tpl file name administration</p>

<p>1 , 2 depth possible set of categories</p>

<p>&nbsp;</p>

<p><strong>External library&nbsp;&nbsp;</strong></p>

<p>CKeditor :&nbsp;<a class="_h8c" href="http://www.tinymce.com/" target="_blank"><cite>http://ckeditor.com/</cite></a></p>

<p>highlight Js :&nbsp;<a href="https://highlightjs.org/">https://highlightjs.org/</a></p>

<p>&nbsp;</p>

<p><strong>Structure</strong></p>

<p>1.html / w.html : view / write html</p>

<p>1.php : Server processing logic</p>

<p>res/js/1.js : view logic processing</p>

<p>res/css/1.css : view css</p>

<p>lib : Externallibrary</p>

<p>config : wiki template&nbsp;config file management</p>

<p>tpl : wiki template</p>
