<!DOCTYPE html>
<html>
<head>
</head>
<body>
<span style="color: #993300;"><span style="color: #993300;"><strong>2. 기본기 - 입력 처리<br /><br /><br /></strong><span style="color: #000000;">- <strong>키패드 입력 감지 (블랙베리 등)<br /><br /></strong></span></span></span>
<pre><code class="java"><strong>KeyDownExampleView.java<br /></strong><br />package org.KeyDownExample;<br /><br />import android.content.Context;<br />import android.graphics.Canvas;<br />import android.graphics.Color;<br />import android.graphics.Paint;<br />import android.view.KeyEvent;<br />import android.view.View;<br /><br /><br />// KeyDownExampleView.java<br /><br /><br />public class KeyDownExampleView extends View {<br /><br /> // 입력된 방향키를 표시하기위한 스트링변수<br /> public String m_dir = "없음";<br /> <br /> public KeyDownExampleView(Context context) {<br />&nbsp;&nbsp; super(context);<br />&nbsp;&nbsp; setFocusable(true); // 키입력을 받기위해 뷰에 포커스를 준다.<br /> }<br /> <br /> @Override<br /> protected void onDraw(Canvas canvas) {<br />&nbsp;&nbsp; // 텍스트 출력<br />&nbsp;&nbsp; Paint p = new Paint(); <br />&nbsp;&nbsp; p.setTextSize(20); // 글자크기를 20으로 지정한다.<br />&nbsp;&nbsp; p.setColor(Color.WHITE); // 글자색을 흰색으로 지정한다.<br />&nbsp;&nbsp; canvas.drawText("입력된 방향키 : " + m_dir, 0, 20, p); <br /> }<br /><br /> @Override<br /> public boolean onKeyDown(int keyCode, KeyEvent event) {<br /> &nbsp;&nbsp;// 왼쪽 방향키를 눌렀을경우<br />&nbsp;&nbsp; if(keyCode == KeyEvent.KEYCODE_DPAD_LEFT)<br />&nbsp;&nbsp; m_dir = "왼쪽";<br />&nbsp;&nbsp; // 오른쪽 방향키를 눌렀을경우<br />&nbsp;&nbsp; if(keyCode == KeyEvent.KEYCODE_DPAD_RIGHT)<br />&nbsp;&nbsp; m_dir = "오른쪽";<br />&nbsp;&nbsp; // 위쪽 방향키를 눌렀을경우<br />&nbsp;&nbsp; if(keyCode == KeyEvent.KEYCODE_DPAD_UP)<br />&nbsp;&nbsp; m_dir = "위쪽";<br />&nbsp;&nbsp; // 아래쪽 방향키를 눌렀을경우<br />&nbsp;&nbsp; if(keyCode == KeyEvent.KEYCODE_DPAD_DOWN)<br />&nbsp;&nbsp; m_dir = "아래쪽";<br /> <br />&nbsp;&nbsp; // 화면을 갱신해준다.<br />&nbsp;&nbsp; invalidate(); <br /><br />&nbsp;&nbsp; return super.onKeyDown(keyCode, event);<br /> }<br />}<br /></code></pre>
<br /><br /> <span style="color: #000000;">- </span><strong><strong><span style="color: #000000;">터치 이벤트 감지 (일반 중요)</span><br /><br /></strong></strong>
<pre><code class="java">TouchEventExampleView.java<br /><br />
package org.TouchEventExample;<br /><br />import android.content.Context;<br />import android.graphics.BitmapFactory;<br />import android.graphics.Canvas;<br />import android.graphics.Color;<br />import android.graphics.Paint;<br />import android.view.MotionEvent;<br />import android.view.View;<br /><br />public class TouchEventExampleView extends View {<br /><br /> private int m_x; // 터치한곳의 x좌표<br /> private int m_y; // 터치한곳의 y좌표<br /> <br /> // 터치이벤트의 액션값을 표시할 문자열변수<br /> private String m_strAction = "없음"; <br /> <br /> public TouchEventExampleView(Context context) {<br /> &nbsp;&nbsp;super(context);<br /> }<br /><br /> @Override<br /> protected void onDraw(Canvas canvas) {<br /> // 아이콘을 표시<br /> &nbsp;&nbsp;canvas.drawBitmap(BitmapFactory.decodeResource(getResources(), R.drawable.icon),m_x, m_y, null);<br /> <br /> &nbsp;&nbsp;Paint p = new Paint(); <br /> &nbsp;&nbsp;p.setTextSize(20); // 글자크기를 20으로 지정한다.<br /> &nbsp;&nbsp;p.setColor(Color.WHITE); // 글자색을 흰색으로 지정한다.<br /> &nbsp;&nbsp;canvas.drawText("이벤트좌표 X :" + m_x +" Y :" + m_y, 0, 20, p); <br /> &nbsp;&nbsp;canvas.drawText("이벤트액션 :" + m_strAction , 0, 40, p);<br /> }<br /> <br /> @Override<br /> public boolean onTouchEvent(MotionEvent event) {<br /> &nbsp;&nbsp;// 좌표를 얻어온다.<br /> &nbsp;&nbsp;m_x = (int) event.getX();<br /> &nbsp;&nbsp;m_y = (int) event.getY();<br /><br /> <br /> &nbsp;&nbsp;// 액션값에 따라 다른처리를 해줄수있다.<br /> &nbsp;&nbsp;if(event.getAction() == MotionEvent.ACTION_DOWN){<br /> &nbsp;&nbsp;&nbsp;&nbsp;// ACTION_DOWN 이 되었을때<br /> &nbsp;&nbsp;&nbsp;&nbsp;m_strAction = "ACTION_DOWN";<br /> &nbsp;&nbsp;}<br /> &nbsp;&nbsp;if(event.getAction() == MotionEvent.ACTION_MOVE){<br /> &nbsp;&nbsp;&nbsp;&nbsp;// ACTION_MOVE 이 되었을때<br /> &nbsp;&nbsp;&nbsp;&nbsp;m_strAction = "ACTION_MOVE";<br /> &nbsp;&nbsp;}<br /> &nbsp;&nbsp;if(event.getAction() == MotionEvent.ACTION_UP){<br /> &nbsp;&nbsp;&nbsp;&nbsp;// ACTION_UP 이 되었을때<br /> &nbsp;&nbsp;&nbsp;&nbsp;m_strAction = "ACTION_UP";<br /> &nbsp;&nbsp;&nbsp;&nbsp;m_x = 0; // 원점으로 이동시켜준다.<br /> &nbsp;&nbsp;&nbsp;&nbsp;m_y = 0;<br /> &nbsp;&nbsp;}<br /><br />&nbsp;&nbsp; invalidate();// 화면을 갱신해준다.<br /> <br /> &nbsp;&nbsp;//return super.onTouchEvent(event);<br /> &nbsp;&nbsp;// ACTION_MOVE 나ACTION_UP 의 액션이벤트를 받을려면 TRUE 를 리턴해주어야한다<br /> &nbsp;&nbsp;return true; <br /> }<br />}<br /></code></pre>
</body>
</html>